# Generated by Django 3.0.3 on 2020-02-05 02:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=200)),
                ('admin_name', models.CharField(max_length=200)),
                ('admin_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('request_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10000)),
                ('client_priority', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('submit_date', models.DateTimeField(auto_now=True)),
                ('target_date', models.DateTimeField(verbose_name='Target Date')),
                ('product_area', models.IntegerField(choices=[(1, 'Assessments'), (2, 'Billing'), (3, 'Recruit'), (4, 'Reports')], default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RequestManager.ClientDetail')),
            ],
        ),
    ]
