# Generated by Django 3.0.3 on 2020-02-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='admin_email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
