# Generated by Django 3.0.3 on 2020-02-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestManager', '0003_auto_20200205_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(default='Please input description of the request'),
        ),
    ]
