# Generated by Django 3.0.3 on 2020-02-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestManager', '0004_auto_20200205_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='submit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='target_date',
            field=models.DateField(verbose_name='Target Date'),
        ),
    ]
