# Generated by Django 3.0.3 on 2020-02-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestManager', '0005_auto_20200205_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='submit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
